// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/sriov.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_sriov_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sriov_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_sriov_proto_rawDescGZIP(), []int{0}
}

type DetailedCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedCapability) Reset() {
	*x = DetailedCapability{}
	mi := &file_proto_sriov_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedCapability) ProtoMessage() {}

func (x *DetailedCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sriov_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedCapability.ProtoReflect.Descriptor instead.
func (*DetailedCapability) Descriptor() ([]byte, []int) {
	return file_proto_sriov_proto_rawDescGZIP(), []int{1}
}

func (x *DetailedCapability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailedCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailedCapability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetailedCapability) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DetailedCapability) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DetailedCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Device struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	PciAddress           string                         `protobuf:"bytes,1,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	Name                 string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Driver               string                         `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Vendor               string                         `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Product              string                         `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	SriovCapable         bool                           `protobuf:"varint,6,opt,name=sriov_capable,json=sriovCapable,proto3" json:"sriov_capable,omitempty"`
	DetailedCapabilities map[string]*DetailedCapability `protobuf:"bytes,7,rep,name=detailed_capabilities,json=detailedCapabilities,proto3" json:"detailed_capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_sriov_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sriov_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_sriov_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Device) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Device) GetSriovCapable() bool {
	if x != nil {
		return x.SriovCapable
	}
	return false
}

func (x *Device) GetDetailedCapabilities() map[string]*DetailedCapability {
	if x != nil {
		return x.DetailedCapabilities
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_sriov_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sriov_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_sriov_proto_rawDescGZIP(), []int{3}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_sriov_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sriov_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_sriov_proto_rawDescGZIP(), []int{4}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_proto_sriov_proto protoreflect.FileDescriptor

const file_proto_sriov_proto_rawDesc = "" +
	"\n" +
	"\x11proto/sriov.proto\x12\x05sriov\"\a\n" +
	"\x05Empty\"\x96\x02\n" +
	"\x12DetailedCapability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12I\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2).sriov.DetailedCapability.ParametersEntryR\n" +
	"parameters\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\x06Device\x12\x1f\n" +
	"\vpci_address\x18\x01 \x01(\tR\n" +
	"pciAddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\x05 \x01(\tR\aproduct\x12#\n" +
	"\rsriov_capable\x18\x06 \x01(\bR\fsriovCapable\x12\\\n" +
	"\x15detailed_capabilities\x18\a \x03(\v2'.sriov.Device.DetailedCapabilitiesEntryR\x14detailedCapabilities\x1ab\n" +
	"\x19DetailedCapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.sriov.DetailedCapabilityR\x05value:\x028\x01\"\x14\n" +
	"\x12ListDevicesRequest\">\n" +
	"\x13ListDevicesResponse\x12'\n" +
	"\adevices\x18\x01 \x03(\v2\r.sriov.DeviceR\adevices2T\n" +
	"\fSRIOVManager\x12D\n" +
	"\vListDevices\x12\x19.sriov.ListDevicesRequest\x1a\x1a.sriov.ListDevicesResponseB&Z$example.com/sriov-plugin/proto;protob\x06proto3"

var (
	file_proto_sriov_proto_rawDescOnce sync.Once
	file_proto_sriov_proto_rawDescData []byte
)

func file_proto_sriov_proto_rawDescGZIP() []byte {
	file_proto_sriov_proto_rawDescOnce.Do(func() {
		file_proto_sriov_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sriov_proto_rawDesc), len(file_proto_sriov_proto_rawDesc)))
	})
	return file_proto_sriov_proto_rawDescData
}

var file_proto_sriov_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_sriov_proto_goTypes = []any{
	(*Empty)(nil),               // 0: sriov.Empty
	(*DetailedCapability)(nil),  // 1: sriov.DetailedCapability
	(*Device)(nil),              // 2: sriov.Device
	(*ListDevicesRequest)(nil),  // 3: sriov.ListDevicesRequest
	(*ListDevicesResponse)(nil), // 4: sriov.ListDevicesResponse
	nil,                         // 5: sriov.DetailedCapability.ParametersEntry
	nil,                         // 6: sriov.Device.DetailedCapabilitiesEntry
}
var file_proto_sriov_proto_depIdxs = []int32{
	5, // 0: sriov.DetailedCapability.parameters:type_name -> sriov.DetailedCapability.ParametersEntry
	6, // 1: sriov.Device.detailed_capabilities:type_name -> sriov.Device.DetailedCapabilitiesEntry
	2, // 2: sriov.ListDevicesResponse.devices:type_name -> sriov.Device
	1, // 3: sriov.Device.DetailedCapabilitiesEntry.value:type_name -> sriov.DetailedCapability
	3, // 4: sriov.SRIOVManager.ListDevices:input_type -> sriov.ListDevicesRequest
	4, // 5: sriov.SRIOVManager.ListDevices:output_type -> sriov.ListDevicesResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sriov_proto_init() }
func file_proto_sriov_proto_init() {
	if File_proto_sriov_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sriov_proto_rawDesc), len(file_proto_sriov_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sriov_proto_goTypes,
		DependencyIndexes: file_proto_sriov_proto_depIdxs,
		MessageInfos:      file_proto_sriov_proto_msgTypes,
	}.Build()
	File_proto_sriov_proto = out.File
	file_proto_sriov_proto_goTypes = nil
	file_proto_sriov_proto_depIdxs = nil
}
